#!/bin/bash

# Strict mode, fail on any error
set -euo pipefail

source ../components/azure-hdinsight/get-hdinsight-kafka-brokers.sh

KAFKA_IN_LISTEN_BROKERS=$KAFKA_BROKERS
KAFKA_IN_LISTEN_SASL_MECHANISM=$KAFKA_SASL_MECHANISM
KAFKA_IN_LISTEN_SECURITY_PROTOCOL=$KAFKA_SECURITY_PROTOCOL
KAFKA_IN_LISTEN_JAAS_CONFIG=$KAFKA_SASL_JAAS_CONFIG
