kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-fileshare-pv-claim
spec:
  storageClassName:  {{ template "fullname" . }}-fileshare-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
