apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}-service-port-patcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "fullname" . }}-service-port-patcher
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services"]
  resourceNames: ["{{ template "fullname" . }}-jobmanager"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "fullname" . }}-service-port-patcher
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ template "fullname" . }}-service-port-patcher
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "fullname" . }}-service-port-patcher
  apiGroup: rbac.authorization.k8s.io
